### ISSUE TITLE
Problem with the mapper

### ISSUE THREAD

**Issue by jrodriguezdiazz** [psauthor/CoreApiFundamentals#4]
![issue](https://user-images.githubusercontent.com/24766287/79415906-768f5a80-7f7c-11ea-931f-ac7046a2e9ae.png)

I do not know what is happening
I need help please @shawnwildermuth

https://github.com/Jorge2000/C_Sharp_API/tree/master/src this is my repo
I'm going for this video of your course https://app.pluralsight.com/course-player?clipId=3a555a91-7c6c-41ea-ae3c-9dcdb2cb0e7f
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request.

AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Camp[] -> CampModel[]
CoreCodeCamp.Data.Camp[] -> CoreCodeCamp.Models.CampModel[] ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
Camp -> CampModel
CoreCodeCamp.Data.Camp -> CoreCodeCamp.Models.CampModel

Type Map configuration:
Camp -> CampModel
CoreCodeCamp.Data.Camp -> CoreCodeCamp.Models.CampModel

Destination Member:
Talks
 ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
Talk -> TalkModel
CoreCodeCamp.Data.Talk -> CoreCodeCamp.Models.TalkModel
   at lambda_method(Closure , Talk , TalkModel , ResolutionContext )
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, IMemberMap memberMap) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 194
   at lambda_method(Closure , Camp[] , CampModel[] , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Camp[] , CampModel[] , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , Camp[] , CampModel[] , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 35
   at CoreCodeCamp.Controllers.CampsController.Get(Boolean includeTalks) in C:\Users\Intellisys\Desktop\CoreApiFundamentals\src\Controllers\CampsController.cs:line 29
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.2.8\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled
```

**Comment by shawnwildermuth** [comment]
Please ask this on the discussion tab of the course. I can't answer questions.

**Comment by jrodriguezdiazz** [comment]
My bad, sorry
